spring:
  datasource:
     url: jdbc:postgresql://localhost:5432/test
     username: postgres
     password: 123456
     dbcp2:
       driver: org.apache.commons.dbcp2.BasicDataSource

  activiti:
      check-process-definitions: false
      process-definition-location-prefix: classpath:/processes/
      #项目启动没有表则创建
      database-schema-update: true
      #相当于日志级别
      history-level: activity
      #不生成流程图png
      createDiagramOnDeploy: false
      #异步启动
      async-executor-activate: true
      #执行流程email通知还没有配置

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

server:
  port: 7777
